services:
  database:
    container_name: subguard_db
    image: postgres:16.9
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: